<?php

namespace bestyii\openapiReader;


use yii\base\InvalidConfigException;
use yii\web\HttpException;
use yii\web\NotFoundHttpException;

/**
 * Class Module
 * @package  bestyii\openapiReader
 */
class Module extends \yii\base\Module
{
    /**
     * @var string
     */
    public $defaultDoc;
    /**
     * @var mixed string or array
     */
    public $path;


    /**
     * @var \Closure
     */
    public $beforeParsing;
    /**
     * Call function
     * @var \Closure
     */
    public $afterRender;


    /**
     * @var \Closure
     */
    public $isDisable;


    /**
     * @var string
     */
    public $controllerNamespace = 'bestyii\openapiReader\controllers';

    /**
     * @throws InvalidConfigException
     */
    public function init()
    {
        if ($this->isDisable()) {
            throw new NotFoundHttpException();
        }

        if (empty($this->path)) {
            throw  new InvalidConfigException('Scan dir not empty or url not empty');
        }
        parent::init(); // TODO: Change the autogenerated stub
    }

    protected function isDisable()
    {
        if (is_callable($this->isDisable)) {
            return call_user_func($this->isDisable);
        }
        return false;
    }

}